name: my-workflow
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Upload Artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: my-files
          path: **/*
      - run: npm ci
      - run: npm test
  deploy:
    needs:  build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - run: npm ci
      - name: run project
        run: npm run build