name: my-workflow
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Using Cache
        id: mycache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: my-cache-${{hashFiles('**/package-lock.json')}} 
      - name: Install dependency
        if: steps.mycache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm test
  deploy:
    needs:  build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Using Cache
        id: mycache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: my-cache-${{hashFiles('**/package-lock.json')}}
      - name: Install Dependency
        if: steps.mycache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run project
        run: npm run build